name: Django application

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    env:
      PIPENV_VENV_IN_PROJECT: 1
      PIPENV_NO_INHERIT: 1
      PIPENV_IGNORE_VIRTUALENVS: 1

    runs-on: ubuntu-latest


    services:
      postgres:
        image: postgres:12
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: django
        ports: [ '5432:5432' ]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        python3 -m pip install --upgrade pip
        pip install -q pipenv codecov flake8
        pipenv sync -d
        pipenv install codecov
        pipenv install --deploy --dev
        pipenv run pytest --cov=pypro
        cp contrib/env-sample .env

    - name: Relatório Coverage
      env:
        CODECOV_TOKEN: 'e9e64690-7443-4174-b56e-23b4137376a1'
      run: |
        pipenv run codecov
